// ============================================
// Silentclean - Log Corruption (5hell Style)
// ============================================

if typeof(safe_file_read) != "function" then
    import_code("/lib/lib_common.gs")
end if

// --- Enhanced Decoy Content (5hell-style) ---
DECOY_LOG = "=== SYSTEM LOG ===" + char(10) +
            "[INFO] System booted at " + current_date + char(10) +
            "[INFO] Network interface up" + char(10) +
            "[INFO] No errors detected" + char(10) +
            "[INFO] Routine maintenance completed" + char(10)

// --- Advanced Decoy Generator with Randomization ---
generate_decoy_content = function()
    // Randomized system service names
    services = ["systemd-tmpfiles", "systemd-journal", "cron-daily", "logrotate", "tmpwatch"]
    service = services[floor(rnd * services.len)]
    
    // Randomized past dates with wider range
    past_dates = ["Mar 04", "Jan 15", "Nov 22", "Feb 28", "Apr 09", "Jun 17", 
                  "Aug 31", "Oct 12", "Dec 05", "May 18", "Jul 23", "Sep 30"]
    fake_date = past_dates[floor(rnd * past_dates.len)]
    
    // Randomized time
    h = floor(rnd * 24)
    m = floor(rnd * 60)
    s = floor(rnd * 60)
    
    if h < 10 then
        hour_str = "0" + str(h)
    else
        hour_str = str(h)
    end if
    if m < 10 then
        min_str = "0" + str(m)
    else
        min_str = str(m)
    end if
    if s < 10 then
        sec_str = "0" + str(s)
    else
        sec_str = str(s)
    end if
    
    // Randomized comment types
    comments = [
        "# System configuration cache",
        "# Runtime configuration data", 
        "# Temporary file management",
        "# Service initialization data",
        "# System maintenance records"
    ]
    comment = comments[floor(rnd * comments.len)]
    
    // Randomized years with current year bias
    fake_years = ["2024", "2025", "2023", "2026"]
    fake_year = fake_years[floor(rnd * fake_years.len)]
    
    // Build decoy content
    decoy = comment + char(10)
    decoy = decoy + "# Generated by " + service + char(10)
    decoy = decoy + "# Do not edit manually" + char(10)
    decoy = decoy + "# Auto-generated on system boot" + char(10)
    decoy = decoy + "# Timestamp: " + fake_date + " " + fake_year + " " + hour_str + ":" + min_str + ":" + sec_str + char(10)
    decoy = decoy + char(10)
    
    // Add standard system entries
    decoy = decoy + "[INFO] System initialized successfully" + char(10)
    decoy = decoy + "[INFO] All services running normally" + char(10)
    decoy = decoy + "[INFO] Disk space: 85% available" + char(10)
    decoy = decoy + "[INFO] Memory usage: 42%" + char(10)
    decoy = decoy + "[INFO] Network status: Connected" + char(10)
    
    return decoy
end function

// --- Corrupt system.log (5hell-style silentclean) ---
silentclean = function(nuke_mode=false)
    comp = get_shell.host_computer
    
    // Primary target: system.log
    log_file = comp.File("/var/system.log")
    if log_file != null then
        decoy_content = generate_decoy_content()
        log_file.set_content(decoy_content)
        log_master("SUCCESS: system.log corrupted with decoy content", "OK")
    end if

    // Nuke mode: corrupt all logs with decoy content
    if nuke_mode then
        log_files = ["/var/system.log", "/var/connection.log", "/var/auth.log"]
        for log_path in log_files
            log_file = comp.File(log_path)
            if log_file != null then
                decoy_content = generate_decoy_content()
                log_file.set_content(decoy_content)
                log_master("SUCCESS: " + log_path + " corrupted (nuke mode)", "OK")
            end if
        end for
    end if
    
    // Remove rkit traces if present (5hell integration)
    rkit = comp.File("/root/rkit")
    if rkit != null then
        result = rkit.delete
        if result == "" then
            log_master("SUCCESS: rkit trace removed", "OK")
        else
            log_master("WARNING: Failed to remove rkit", "WARN")
        end if
    end if
    
    // Clean trash folders
    trash_paths = ["/root/.Trash"]
    home = comp.File("/home")
    if home != null then
        home_folders = home.get_folders
        if home_folders != null then
            for user_folder in home_folders
                if user_folder != null then
                    trash_paths.push("/home/" + user_folder.name + "/.Trash")
                end if
            end for
        end if
    end for
    for tp in trash_paths
        trash = comp.File(tp)
        if trash != null then
            result = trash.delete
            if result == "" then
                log_master("SUCCESS: Cleaned " + tp, "OK")
            end if
        end if
    end for
end function

// --- Legacy wrapper for compatibility ---
wipe_logs = function(comp=null)
    if comp == null then comp = get_shell.host_computer
    silentclean(false)
end function

// --- Aggressive wiping (nuke mode) ---
silentclean_aggressive = function()
    silentclean(true)
end function
