// wipe_logs.gs - Log wiper with silentclean-style corruption
// Upgraded from simple zeroing to make detection harder
// Usage: import_code("/scripts/utils/wipe_logs.gs")
if typeof(safe_file_read) != "function" then
    import_code("/lib/lib_common.gs")
end if

// Generate a decoy that looks like legitimate system files
// Enhanced randomization to avoid forensic signatures across infections
generate_decoy_content = function()
    // Randomized system service names
    services = ["systemd-tmpfiles", "systemd-journal", "cron-daily", "logrotate", "tmpwatch"]
    service = services[floor(rnd * services.len)]
    
    // Randomized past dates with wider range
    past_dates = ["Mar 04", "Jan 15", "Nov 22", "Feb 28", "Apr 09", "Jun 17", 
                  "Aug 31", "Oct 12", "Dec 05", "May 18", "Jul 23", "Sep 30"]
    fake_date = past_dates[floor(rnd * past_dates.len)]
    
    // Randomized time
    h = floor(rnd * 24)
    m = floor(rnd * 60)
    s = floor(rnd * 60)
    
    if h < 10 then
        hour_str = "0" + str(h)
    else
        hour_str = str(h)
    end if
    if m < 10 then
        min_str = "0" + str(m)
    else
        min_str = str(m)
    end if
    if s < 10 then
        sec_str = "0" + str(s)
    else
        sec_str = str(s)
    end if
    
    // Randomized comment types
    comments = [
        "# System configuration cache",
        "# Runtime configuration data", 
        "# Temporary file management",
        "# Service initialization data",
        "# System maintenance records"
    ]
    comment = comments[floor(rnd * comments.len)]
    
    // Randomized years with current year bias
    fake_years = ["2024", "2025", "2023", "2026"]
    fake_year = fake_years[floor(rnd * fake_years.len)]
    
    // Build decoy content
    decoy = comment + char(10)
    decoy = decoy + "# Generated by " + service + char(10)
    decoy = decoy + "# Do not edit manually" + char(10)
    decoy = decoy + "# Auto-generated on system boot" + char(10)
    decoy = decoy + "# Timestamp: " + fake_date + " " + fake_year + " " + hour_str + ":" + min_str + ":" + sec_str + char(10)
    decoy = decoy + char(10)
    
    // Randomized directory entries with different permissions
    dirs = [
        {"path": "/run/user", "perm": "0755", "uid": "root", "gid": "root"},
        {"path": "/tmp", "perm": "1777", "uid": "root", "gid": "root"},
        {"path": "/var/cache", "perm": "0755", "uid": "root", "gid": "root"},
        {"path": "/var/tmp", "perm": "1777", "uid": "root", "gid": "root"}
    ]
    
    // Random subset of directories
    selected_dirs = []
    num_dirs = 2 + floor(rnd * 3)  // 2-4 directories
    for i in range(0, num_dirs - 1)
        idx = floor(rnd * dirs.len)
        if selected_dirs.indexOf(dirs[idx]) == -1 then
            selected_dirs.push(dirs[idx])
        end if
    end for
    
    // Add randomized directory entries
    for dir in selected_dirs
        decoy = decoy + "d " + dir.path + " " + dir.perm + " " + dir.uid + " " + dir.gid + " - - -" + char(10)
    end for
    
    // Randomized file entries
    files = [
        {"path": "/var/run/utmp", "perm": "0644", "uid": "root", "gid": "root"},
        {"path": "/var/log/wtmp", "perm": "0664", "uid": "root", "gid": "root"},
        {"path": "/etc/machine-id", "perm": "0644", "uid": "root", "gid": "root"}
    ]
    
    // Random subset of files
    selected_files = []
    num_files = 1 + floor(rnd * 2)  // 1-2 files
    for i in range(0, num_files - 1)
        idx = floor(rnd * files.len)
        if selected_files.indexOf(files[idx]) == -1 then
            selected_files.push(files[idx])
        end if
    end for
    
    // Add randomized file entries
    for file in selected_files
        decoy = decoy + "f " + file.path + " " + file.perm + " " + file.uid + " " + file.gid + " - - -" + char(10)
    end for
    
    // Add some random noise entries
    noise_entries = [
        "# Cleanup interval: 3600",
        "# Max entries: 1000",
        "# Compression: enabled",
        "# Backup: daily"
    ]
    
    num_noise = 1 + floor(rnd * 3)  // 1-3 noise entries
    for i in range(0, num_noise - 1)
        noise = noise_entries[floor(rnd * noise_entries.len)]
        decoy = decoy + "# " + noise + char(10)
    end for
    
    return decoy
end function

safe_delete = function(file_obj, path)
    if file_obj == null then return false
    
    // Check write permission on parent directory
    parts = path.split("/")
    filename = parts.pop
    parent_path = parts.join("/")
    if parent_path == "" then parent_path = "/"
    
    parent = get_shell.host_computer.File(parent_path)
    if parent == null then return false
    
    // Try deletion
    result = file_obj.delete
    if result == "" then return true
    
    return false
end function

wipe_logs = function(comp)
    if comp == null then comp = get_shell.host_computer
    
    // Standard logs - zero them
    logs = ["/var/log/auth.log", "/var/log/syslog", "/var/log/kern.log"]
    for logPath in logs
        f = comp.File(logPath)
        if f != null then f.set_content("")
    end for
    
    // System.log - corrupt with decoy (harder to detect than deletion)
    syslog = comp.File("/var/system.log")
    if syslog != null then
        decoy = generate_decoy_content()
        syslog.set_content(decoy)
    end if
    
    // Remove rkit traces if present
    rkit = comp.File("/root/rkit")
    if rkit != null then
        if not safe_delete(rkit, "/root/rkit") then
            // Log failure but continue
        end if
    end if
    
    // Clean trash folders
    trash_paths = ["/root/.Trash"]
    home = comp.File("/home")
    if home != null then
        home_folders = home.get_folders
        if home_folders != null then
            for user_folder in home_folders
                if user_folder != null then
                    trash_paths.push("/home/" + user_folder.name + "/.Trash")
                end if
            end for
        end if
    end if
    for tp in trash_paths
        trash = comp.File(tp)
        if trash != null then
            safe_delete(trash, tp)
        end if
    end for
end function

// Note: For aggressive wiping, use wipe_logs_aggressive.gs instead
