// wipe_logs.gs - Log wiper with silentclean-style corruption
// Upgraded from simple zeroing to make detection harder
// Usage: import_code("/scripts/utils/wipe_logs.gs")
if typeof(safe_file_read) != "function" then
    import_code("/lib/lib_common.gs")
end if

// Generate a decoy that looks like legitimate system files
// Uses randomized timestamp to avoid forensic signature across infections
generate_decoy_content = function()
    past_dates = ["Mar 04", "Jan 15", "Nov 22", "Feb 28", "Apr 09", "Jun 17"]
    fake_date = past_dates[floor(rnd * past_dates.len)]
    h = floor(rnd * 6)
    m = 40 + floor(rnd * 19)
    if h < 10 then
        hour_str = "0" + str(h)
    else
        hour_str = str(h)
    end if
    if m < 10 then
        min_str = "0" + str(m)
    else
        min_str = str(m)
    end if
    decoy = "# System configuration cache" + char(10)
    decoy = decoy + "# Generated by systemd-tmpfiles" + char(10)
    decoy = decoy + "# Do not edit manually" + char(10)
    // Vary the year to avoid forensic signature
    fake_years = ["2024", "2025", "2023"]
    fake_year = fake_years[floor(rnd * fake_years.len)]
    decoy = decoy + "# Timestamp: " + fake_date + " " + fake_year + " " + hour_str + ":" + min_str + ":17" + char(10)
    decoy = decoy + char(10)
    decoy = decoy + "d /run/user 0755 root root - - -" + char(10)
    decoy = decoy + "d /tmp 1777 root root - - -" + char(10)
    decoy = decoy + "d /var/cache 0755 root root - - -" + char(10)
    decoy = decoy + "f /var/run/utmp 0644 root root - - -" + char(10)
    return decoy
end function

safe_delete = function(file_obj, path)
    if file_obj == null then return false
    
    // Check if file exists
    if file_obj.path == null then return false
    
    // Check write permission on parent directory
    parts = path.split("/")
    filename = parts.pop
    parent_path = parts.join("/")
    if parent_path == "" then parent_path = "/"
    
    parent = get_shell.host_computer.File(parent_path)
    if parent == null then return false
    
    // Try deletion
    result = file_obj.delete
    if result == "" then return true
    
    return false
end function

wipe_logs = function(comp)
    if comp == null then comp = get_shell.host_computer
    
    // Standard logs - zero them
    logs = ["/var/log/auth.log", "/var/log/syslog", "/var/log/kern.log"]
    for logPath in logs
        f = comp.File(logPath)
        if f != null then f.set_content("")
    end for
    
    // System.log - corrupt with decoy (harder to detect than deletion)
    syslog = comp.File("/var/system.log")
    if syslog != null then
        decoy = generate_decoy_content()
        syslog.set_content(decoy)
    end if
    
    // Remove rkit traces if present
    rkit = comp.File("/root/rkit")
    if rkit != null then
        if not safe_delete(rkit, "/root/rkit") then
            // Log failure but continue
        end if
    end if
    
    // Clean trash folders
    trash_paths = ["/root/.Trash"]
    home = comp.File("/home")
    if home != null then
        home_folders = home.get_folders
        if home_folders != null then
            for user_folder in home_folders
                if user_folder != null then
                    trash_paths.push("/home/" + user_folder.name + "/.Trash")
                end if
            end for
        end if
    end if
    for tp in trash_paths
        trash = comp.File(tp)
        if trash != null then
            safe_delete(trash, tp)
        end if
    end for
end function

// Note: For aggressive wiping, use wipe_logs_aggressive.gs instead
