// wipe_logs.gs - Log wiper with silentclean-style corruption
// Upgraded from simple zeroing to make detection harder
// Usage: import_code("/scripts/utils/wipe_logs.gs")

// Generate a decoy that looks like legitimate system files
generate_decoy_content = function()
    decoy = "# System configuration cache" + char(10)
    decoy = decoy + "# Generated by systemd-tmpfiles" + char(10)
    decoy = decoy + "# Do not edit manually" + char(10)
    decoy = decoy + "# Timestamp: " + current_date + char(10)
    decoy = decoy + char(10)
    decoy = decoy + "d /run/user 0755 root root - - -" + char(10)
    decoy = decoy + "d /tmp 1777 root root - - -" + char(10)
    decoy = decoy + "d /var/cache 0755 root root - - -" + char(10)
    decoy = decoy + "f /var/run/utmp 0644 root root - - -" + char(10)
    return decoy
end function

safe_delete = function(file_obj, path)
    if file_obj == null then return false
    
    // Check if file exists
    if file_obj.path == null then return false
    
    // Check write permission on parent directory
    parts = path.split("/")
    filename = parts.pop
    parent_path = parts.join("/")
    if parent_path == "" then parent_path = "/"
    
    parent = get_shell.host_computer.File(parent_path)
    if parent == null then return false
    
    // Try deletion
    result = file_obj.delete
    if result == "" then return true
    
    return false
end function

wipe_logs = function(comp)
    if comp == null then comp = get_shell.host_computer
    
    // Standard logs - zero them
    logs = ["/var/log/auth.log", "/var/log/syslog", "/var/log/kern.log"]
    for logPath in logs
        f = comp.File(logPath)
        if f != null then f.set_content("")
    end for
    
    // System.log - corrupt with decoy (harder to detect than deletion)
    syslog = comp.File("/var/system.log")
    if syslog != null then
        decoy = generate_decoy_content()
        syslog.set_content(decoy)
    end if
    
    // Remove rkit traces if present
    rkit = comp.File("/root/rkit")
    if rkit != null then
        if not safe_delete(rkit, "/root/rkit") then
            // Log failure but continue
        end if
    end if
    
    // Clean trash folders
    trash_paths = ["/root/.Trash"]
    home = comp.File("/home")
    if home != null then
        home_folders = home.get_folders
        if home_folders != null then
            for user_folder in home_folders
                if user_folder != null then
                    trash_paths.push("/home/" + user_folder.name + "/.Trash")
                end if
            end for
        end if
    end if
    for tp in trash_paths
        trash = comp.File(tp)
        if trash != null then
            safe_delete(trash, tp)
        end if
    end for
end function

// Aggressive wipe - also removes /etc/passwd and sensitive files
wipe_logs_aggressive = function(comp)
    if comp == null then comp = get_shell.host_computer
    
    // Standard wipe first
    wipe_logs(comp)
    
    // Remove /etc/passwd - check permissions first
    passwd = comp.File("/etc/passwd")
    if passwd != null then
        // Only delete if we're root AND passwd is a regular file (not a symlink)
        if accessLevel(get_shell) == "root" and passwd.is_binary == 0 then
            // Create a minimal backup first
            backup = comp.File("/etc/passwd.bak")
            if backup == null then
                comp.touch("/etc", "passwd.bak")
                backup = comp.File("/etc/passwd.bak")
            end if
            if backup != null then
                // Only delete if backup succeeded
                passwd.move("/etc/passwd.bak")
            end if
        end if
    end if
    
    // Remove Bank.txt and Mail.txt across all users
    bank_paths = ["/root/Config/Bank.txt"]
    mail_paths = ["/root/Config/Mail.txt"]
    home = comp.File("/home")
    if home != null then
        home_folders = home.get_folders
        if home_folders != null then
            for user_folder in home_folders
                if user_folder != null and user_folder.name != "guest" then
                    bank_paths.push("/home/" + user_folder.name + "/Config/Bank.txt")
                    mail_paths.push("/home/" + user_folder.name + "/Config/Mail.txt")
                end if
            end for
        end if
    end if
    
    for bp in bank_paths
        bf = comp.File(bp)
        if bf != null and bf.has_permission("w") then
            bf.delete
        end if
    end for
    for mp in mail_paths
        mf = comp.File(mp)
        if mf != null and mf.has_permission("w") then
            mf.delete
        end if
    end for
end function
